name: Build and Push Docker image

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-18.04  # 指定 Ubuntu 版本

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-docker@v2
        with:
          version: 20.10.9  # 指定 Docker 版本

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build the Docker image
        run: docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/ipopt-docker:latest

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ipopt-docker:latest
