name: Build and Push Docker image

on:
  push:
    branches:
      - main  # 当代码推送到 main 分支时触发
    tags:
      - '*'  # 当有标签推送时触发
  pull_request:
    branches:
      - main  # 当向 main 分支提交 PR 时触发

jobs:
  build:
    runs-on: ubuntu-20.04  # 使用 Ubuntu 18.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'  # 仅在非 PR 事件中执行
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract GitHub tag
        id: extract_tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

      - name: Set Docker image tag
        id: image_tag
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            echo ::set-output name=tag::latest
          elif [ "${GITHUB_REF}" == "${{ github.event.pull_request.head.ref }}" ]; then
            echo ::set-output name=tag::pr-${{ github.event.pull_request.number }}
          else
            echo ::set-output name=tag::${{ steps.extract_tag.outputs.tag }}
        if: github.event_name != 'pull_request' || github.event_name == 'pull_request'

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false  # 默认不推送
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ipopt-docker:${{ steps.image_tag.outputs.tag }}
        if: github.event_name == 'pull_request'

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true  # 推送镜像
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ipopt-docker:${{ steps.image_tag.outputs.tag }}
        if: github.event_name != 'pull_request'
